# See https://dart.dev/guides/language/analysis-options
include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    unused_import: warning
    dead_code: warning
    missing_return: error
    unused_local_variable: warning
    always_declare_return_types: error
    avoid_print: warning
    prefer_const_constructors: warning
    prefer_const_literals_to_create_immutables: warning
    prefer_final_locals: warning
    unnecessary_this: warning
    unnecessary_new: warning
    prefer_single_quotes: warning
    prefer_interpolation_to_compose_strings: warning
    prefer_collection_literals: warning
    prefer_typing_uninitialized_variables: warning
    avoid_return_types_on_setters: warning
    avoid_types_on_closure_parameters: warning
    avoid_init_to_null: warning
    avoid_annotating_with_dynamic: warning
    avoid_empty_else: warning
    avoid_function_literals_in_foreach_calls: warning
    avoid_redundant_argument_values: warning
    avoid_returning_null: warning
    avoid_returning_this: warning
    avoid_setters_without_getters: warning
    avoid_shadowing_type_parameters: warning
    avoid_single_cascade_in_expression_statements: warning
    avoid_unnecessary_containers: warning
    avoid_unused_constructor_parameters: warning
    camel_case_types: warning
    cancel_subscriptions: warning
    cascade_invocations: warning
    close_sinks: warning
    comment_references: warning
    control_flow_in_finally: warning
    curly_braces_in_flow_control_structures: warning
    diagnostic_describe_all_properties: warning
    directives_ordering: warning
    empty_catches: warning
    empty_constructor_bodies: warning
    empty_statements: warning
    file_names: warning
    hash_and_equals: warning
    implementation_imports: warning
    invariant_booleans: warning
    iterable_contains_unrelated_type: warning
    join_return_with_assignment: warning
    leading_newlines_in_multiline_strings: warning
    library_names: warning
    library_prefixes: warning
    list_remove_unrelated_type: warning
    literal_only_boolean_expressions: warning
    missing_whitespace_between_adjacent_strings: warning
    no_adjacent_strings_in_list: warning
    no_duplicate_case_values: warning
    non_constant_identifier_names: warning
    null_closures: warning
    omit_local_variable_types: warning
    one_member_abstracts: warning
    only_throw_errors: warning
    overridden_fields: warning
    package_api_docs: warning
    package_names: warning
    package_prefixed_library_names: warning
    parameter_assignments: warning
    prefer_adjacent_string_concatenation: warning
    prefer_asserts_in_initializer_lists: warning
    prefer_bool_in_asserts: warning
    prefer_conditional_assignment: warning
    prefer_const_constructors_in_immutables: warning
    prefer_const_declarations: warning
    prefer_const_literals_to_create_immutables: warning
    prefer_constructors_over_static_methods: warning
    prefer_contains: warning
    prefer_double_quotes: warning
    prefer_equal_for_default_values: warning
    prefer_expression_function_bodies: warning
    prefer_final_fields: warning
    prefer_final_in_for_each: warning
    prefer_final_locals: warning
    prefer_for_elements_to_map_fromIterable: warning
    prefer_foreach: warning
    prefer_function_declarations_over_variables: warning
    prefer_generic_function_type_aliases: warning
    prefer_if_elements_to_conditional_expressions: warning
    prefer_initializing_formals: warning
    prefer_inlined_adds: warning
    prefer_int_literals: warning
    prefer_is_empty: warning
    prefer_is_not_empty: warning
    prefer_iterable_whereType: warning
    prefer_mixin: warning
    prefer_null_aware_operators: warning
    prefer_relative_imports: warning
    prefer_spread_collections: warning
    prefer_typing_uninitialized_variables: warning
    provide_deprecation_message: warning
    public_member_api_docs: warning
    recursive_getters: warning
    slash_for_doc_comments: warning
    sort_child_properties_last: warning
    sort_constructors_first: warning
    sort_unnamed_constructors_first: warning
    test_types_in_equals: warning
    throw_in_finally: warning
    type_annotate_public_apis: warning
    type_init_formals: warning
    unawaited_futures: warning
    unnecessary_await_in_return: warning
    unnecessary_brace_in_string_interps: warning
    unnecessary_const: warning
    unnecessary_getters_setters: warning
    unnecessary_lambdas: warning
    unnecessary_null_aware_assignments: warning
    unnecessary_null_in_if_null_operators: warning
    unnecessary_overrides: warning
    unnecessary_parenthesis: warning
    unnecessary_raw_strings: warning
    unnecessary_statements: warning
    unnecessary_string_escapes: warning
    unnecessary_string_interpolations: warning
    unnecessary_this: warning
    unrelated_type_equality_checks: warning
    use_full_hex_values_for_flutter_colors: warning
    use_function_type_syntax_for_parameters: warning
    use_key_in_widget_constructors: warning
    use_late_for_private_fields_and_variables: warning
    use_named_constants: warning
    use_rethrow_when_possible: warning
    use_setters_to_change_properties: warning
    use_string_buffers: warning
    use_to_and_as_if_applicable: warning
    valid_regexps: warning
    void_checks: warning
